name: Build JAR File

on:
  push:
    branches: master

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
         java-version: 8
      - name: Build with Maven
#        Runs the mvn command to build the application. The -B flag tells Maven to run in batch mode, which is useful for non-interactive builds.
#        The package goal is used to create a JAR file from the project.
#        The --file pom.xml specifies the location of the Maven project file.
        run: mvn -B package --file pom.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCdSpringBoot
          path: target/CiCdSpringBoot.jar