name: Build and Deploy

on:
  push:
    branches:
      - docker

env:
  IMAGE_NAME: my-docker-image
  DOCKER_BUILDKIT: 1

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Unit tests
        run: mvn test

      - name: Code quality analysis
        run: |
          mvn pmd:pmd
          mvn jacoco:report

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CiCdSpringBoot.jar
          path: target/CiCdSpringBoot.jar

  build-docker:
    runs-on: ubuntu-latest
    needs: build-jar
    if: success('build-jar')

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            JAR_FILE=target/CiCdSpringBoot.jar
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
