name: Build and Deploy

on:
  push:
    branches:
      - docker

env:
  IMAGE_NAME: cicdspringboot
  DOCKER_BUILDKIT: 1

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DoutputDirectory=./target

      - name: Unit tests
        run: mvn test

      - name: Code quality analysis
        run: |
          mvn pmd:pmd
          mvn jacoco:report

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: CiCdSpringBoot.jar
          path: target/CiCdSpringBoot.jar

      - name: list dir
        run: |
          ls

      - name: list dir target
        run: |
          cd target
          ls

      - name: Cache target folder
        uses: actions/cache@v2
        with:
          path: target/*.jar
          key: ${{ runner.os }}-target-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-target-

#      - name: Build the Docker image
#        if: success()
#        run: |
#          docker build . -t ${{ env.IMAGE_NAME }} -f Dockerfile

  build-docker:
    runs-on: ubuntu-latest
    needs: build-jar
    if: success('build-jar')

    steps:
      - uses: actions/checkout@v2

      - name: Load cached target folder
        uses: actions/cache@v2
        with:
          path: target/*.jar
          key: ${{ runner.os }}-target-${{ hashFiles('**/pom.xml') }}

      - name: list dir
        run: |
          ls

      - name: list dir target
        run: |
          cd target
          ls

      - name: Build the Docker image
        run: |
          docker build . -t ${{ env.IMAGE_NAME }} -f Dockerfile
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
#          build-args: |
#            JAR_FILE=target/*.jar
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
